[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "integration: mark test as integration",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
