"""fixed fsrs and final card cascading

Revision ID: 2cd581fdb808
Revises: 442327ee10cd
Create Date: 2025-08-20 11:44:43.258442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd581fdb808'
down_revision: Union[str, Sequence[str], None] = '442327ee10cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('flashcard_final_cards_flashcard_id_fkey'), 'flashcard_final_cards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcard_final_cards', 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('flashcard_fsrs_flashcard_id_fkey'), 'flashcard_fsrs', type_='foreignkey')
    op.create_foreign_key(None, 'flashcard_fsrs', 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcard_fsrs', type_='foreignkey')
    op.create_foreign_key(op.f('flashcard_fsrs_flashcard_id_fkey'), 'flashcard_fsrs', 'flashcards', ['flashcard_id'], ['id'])
    op.drop_constraint(None, 'flashcard_final_cards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcard_final_cards_flashcard_id_fkey'), 'flashcard_final_cards', 'flashcards', ['flashcard_id'], ['id'])
    # ### end Alembic commands ###
