"""fixed discussion cascading

Revision ID: 442327ee10cd
Revises: 
Create Date: 2025-08-20 11:43:21.526393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442327ee10cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('flashcard_discussions_flashcard_id_fkey'), 'flashcard_discussions', type_='foreignkey')
    op.create_foreign_key(None, 'flashcard_discussions', 'flashcards', ['flashcard_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcard_discussions', type_='foreignkey')
    op.create_foreign_key(op.f('flashcard_discussions_flashcard_id_fkey'), 'flashcard_discussions', 'flashcards', ['flashcard_id'], ['id'])
    # ### end Alembic commands ###
